### ISSUE TITLE
Camera Controller

### ISSUE THREAD

**Issue by SirePi** [SirePi/duality-companion#1]
- ~~Shake~~
- Object tracking
- ~~Make target area visible~~

Should implement fade in/out?

**Comment by ChristianGreiner** [comment]
What do you mean with **_fade in/out_** exactly ?

**Comment by SirePi** [comment]
Make the camera fade in or fade out to a color

**Comment by mfep** [comment]
All the other functions have to do something with the Camera's Transform, thus fading is a little bit out of place. What about rethinking this question once the other Camera stuff is ready?

**Comment by SirePi** [comment]
@ChristianGreiner already did the fader, so that's done :)
I finished implementing the camera shake. A simple one with the capability to be extended if needed by providing a custom displacement function.

**Comment by SirePi** [comment]
Done.
