### ISSUE TITLE
Infinite scrolling renderer

### ISSUE THREAD

**Issue by SirePi** [SirePi/duality-companion#3]
Since I managed to do the CheckeredBackground for diagnostics, I was wondering if it would be helpful to implement a generic infinite scrolling SpriteRenderer, that could be used as background for a game.

Properties that it should expose:
* a Material
* a Scale factor
* if the scrolling should be made on the X, Y, or both
* scrolling speed multiplier?

Should I go for it?

**Comment by ChristianGreiner** [comment]
Yes, please! 
 
The default SpriteRenderer of Duality supports already this feature in some ways, but some properties and stuff are not designed for this purposes, so you have to implement your own renderer with some tweaks...

I used this infinite scrolling renderer for my space game to display an infinite star background.

Maybe we could name this renderer like "PlaneRenderer" or something like that...?

Original Issue
https://github.com/AdamsLair/duality/issues/325

**Comment by SirePi** [comment]
Ooh, didn't know there was an issue about this.. 
alright, will do

**Comment by mfep** [comment]
Just tried it, very smooth so far!

**Comment by SirePi** [comment]
Fixed one final issue. Still to document the properties. Closing anyway.

**Comment by SirePi** [comment]
Reopening to implement some of the missing requirements described in https://github.com/AdamsLair/duality/issues/161
* AlignToPixelGrid
* VisibilityGroup

**Comment by SirePi** [comment]
Forgot to close..
